// SPDX-License-Identifier: Apache-2.0
/// @file   plugins/links/tls/plugin_entry.cpp
/// @brief  Plugin entry surface generated by the `GN_LINK_PLUGIN`
///         macro from `sdk/cpp/link_plugin.hpp`.

#include "tls.hpp"

#include <sdk/cpp/link_plugin.hpp>

GN_LINK_PLUGIN(::gn::link::tls::TlsLink, "tls")
